"""<your message>

Revision ID: 6227f7459e94
Revises: a50cde241c4b
Create Date: 2023-11-29 20:36:24.252751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6227f7459e94'
down_revision = 'a50cde241c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bakery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bakeries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bakeries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bakery')
    # ### end Alembic commands ###
